server:
  port: 8888

spring:
  # 配置redis
  redis:
    database: 0
    port: 6480
    password:
  # 配置mysql数据库
  datasource:
    url: jdbc:mysql://localhost:3406/virus_isolation?autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/virus_isolation?authSource=admin&authMechanism=SCRAM-SHA-1

  # 配置缓存
  cache:
    redis:
      time-to-live: 1d



logging:
  level:
    org.hhoa.vi: debug

file:
  upload:
    path: /projects/public/data/uploads/  #文件上传目标路径
    baseUrl: http://localhost/uploads/
